FROM corebuild

FROM scratch

COPY --from=corebuild /go/src/github.com/notegio/openrelay/bin/allowancemonitor /allowancemonitor

COPY --from=corebuild /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

CMD ["/allowancemonitor", "redis:6379", "${ETHEREUM_RPC}", "queue://newblocks", "queue://recordspend", "${EXCHANGE_ADDRESS}"]
