FROM corebuild

FROM scratch

COPY --from=corebuild /go/src/github.com/notegio/openrelay/bin/canceluptomonitor /canceluptomonitor

COPY --from=corebuild /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

CMD ["/canceluptomonitor", "redis:6379", "${ETHEREUM_RPC}", "queue://newblocks", "queue://recordcancel", "${EXCHANGE_ADDRESS}"]
