FROM corebuild

FROM scratch

COPY --from=corebuild /go/src/github.com/notegio/openrelay/bin/spendmonitor /spendmonitor

CMD ["/spendmonitor", "redis:6379", "${ETHEREUM_RPC}", "queue://newblocks", "queue://recordspend", "${EXCHANGE_ADDRESS}"]
