FROM corebuild

FROM scratch

COPY --from=corebuild /go/src/github.com/notegio/openrelay/bin/erc721approvalmonitor /erc721approvalmonitor

COPY --from=corebuild /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

CMD ["/erc721approvalmonitor", "redis:6379", "${ETHEREUM_RPC}", "queue://newblocks", "queue://recordspend", "${EXCHANGE_ADDRESS}"]
