FROM corebuild

FROM scratch

COPY --from=corebuild /go/src/github.com/notegio/openrelay/bin/multisigmonitor /multisigmonitor

CMD ["/multisigmonitor", "redis:6379", "${ETHEREUM_RPC}", "queue://newblocks", "${EXCHANGE_ADDRESS}"]
