FROM corebuild

FROM scratch

COPY --from=corebuild /go/src/github.com/notegio/openrelay/bin/affiliatemonitor /affiliatemonitor

COPY --from=corebuild /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

CMD ["/affiliatemonitor", "redis:6379", "${ETHEREUM_RPC}", "queue://newblocks", "${EXCHANGE_ADDRESS}"]
