FROM corebuild

FROM scratch

COPY --from=corebuild /go/src/github.com/notegio/openrelay/bin/fillmonitor /fillmonitor

COPY --from=corebuild /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

CMD ["/fillmonitor", "redis:6379", "${ETHEREUM_RPC}", "queue://newblocks", "queue://ordersfilled", "${EXCHANGE_ADDRESS}"]
